import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

/** Deviations from the ultracite preset, each with its reason. */
export default defineConfig({
  ...ultracite,
  ignorePatterns: [
    ...(ultracite.ignorePatterns ?? []),
    // Generated by `bun run ui:add` from the shadcn preset and never edited by
    // hand (see AGENTS.md); re-running the generator would undo any change.
    "components/ui",
    // Skills vendored from other repos and pinned by hash in
    // `skills-lock.json`; reformatting them invalidates the lockfile and is
    // lost on the next update anyway.
    ".agents/skills/code-review",
    ".agents/skills/codebase-design",
    ".agents/skills/improve-codebase-architecture",
    ".agents/skills/shadcn",
    ".agents/skills/vercel-*",
    ".agents/skills/web-design-guidelines",
    // Curated content, reviewed with `bun run data:check`; the formatter must
    // not silently reindent it.
    "data",
    // A frozen design prototype kept for reference, not living source.
    "docs/prototype.html",
  ],
  // AGENTS.md and docs/ are hard-wrapped by hand so prose diffs stay readable
  // line by line; ultracite's "never" collapses every paragraph into one line.
  proseWrap: "preserve",
  // package.json is grouped by hand (identity, engines, scripts, dependencies)
  // so the file reads top-down; alphabetising it only produces review churn.
  sortPackageJson: false,
  // The code already had trailing commas in multi-line parameter lists, and
  // they keep a future diff to the line that actually changed.
  trailingComma: "all",
});
