import { defineConfig } from "oxlint";
import type { DummyRuleMap } from "oxlint";
import core from "ultracite/oxlint/core";
import { jsPluginSettings, selectJsPlugins } from "ultracite/oxlint/js-plugins";
import next from "ultracite/oxlint/next";
import nextJsPlugins from "ultracite/oxlint/next/js-plugins";
import react from "ultracite/oxlint/react";

const jsPlugins = selectJsPlugins(["react-doctor"]);

/**
 * The worlds a module under `lib/` may not reach into by itself, each with the
 * adapter that owns it. `scripts/check-seams.ts` carries the other half of the
 * invariant – the greps a lint rule cannot express.
 */
const RESTRICTED_GLOBALS = [
  {
    message: "The DOM belongs to components/; lib/ takes values.",
    name: "document",
  },
  { message: "`fetch` belongs to lib/use-fetch.ts.", name: "fetch" },
  { message: "The hash belongs to lib/hash-adapter.ts.", name: "history" },
  { message: "The hash belongs to lib/hash-adapter.ts.", name: "location" },
  {
    message: "Web storage belongs to lib/use-stored.ts.",
    name: "localStorage",
  },
  {
    message: "Media queries belong to lib/use-media-query.ts.",
    name: "matchMedia",
  },
  {
    message: "The DOM belongs to components/; lib/ takes values.",
    name: "MutationObserver",
  },
  {
    message: "The platform belongs to the adapters in lib/use-*.ts.",
    name: "navigator",
  },
  {
    message: "The DOM belongs to components/; lib/ takes values.",
    name: "ResizeObserver",
  },
  {
    message: "Web storage belongs to lib/use-stored.ts.",
    name: "sessionStorage",
  },
  {
    message: "The browser belongs to the adapters in lib/use-*.ts.",
    name: "window",
  },
];

/** MapLibre is driven from two adapters; everything else under `lib/` may read its types. */
const MAPLIBRE = {
  allowTypeImports: true,
  message:
    "MapLibre is an adapter's business: the map is driven from components/map/apply-scene.ts and apply-camera.ts. Types are fine.",
  name: "maplibre-gl",
};

/**
 * The dictionaries are the server's (plan 08, docs/architecture.md): a page's
 * words reach the browser as a value from its layout, one language per page
 * (`I18nProvider`), and a component asks `useT()`. A value import of either
 * dictionary from code the browser runs would ship both languages to every
 * page; the `Messages` type is fine anywhere.
 */
const DICTIONARIES = [
  "@/lib/i18n/dictionaries",
  "@/lib/i18n/messages.de",
  "@/lib/i18n/messages.en",
].map((name) => ({
  allowTypeImports: true,
  message:
    "The words reach the browser as a value (`useT()` in a component, an argument in lib/); the dictionaries are for the server, the scripts and the tests.",
  name,
}));

/**
 * The same rule again for one adapter, minus the globals it owns – so the
 * file is still held to every world it is *not* a window onto.
 */
const except = (...owned: string[]): DummyRuleMap => ({
  "no-restricted-globals": [
    "error",
    {
      checkGlobalObject: true,
      globals: RESTRICTED_GLOBALS.filter((g) => !owned.includes(g.name)),
    },
  ],
});

/**
 * oxlint replaces ESLint here: its `nextjs` and `react` plugins cover what
 * `eslint-config-next` used to, React Compiler rules included.
 *
 * This file records only where the project deviates from the ultracite preset,
 * and every deviation states why. Prefer adding a reasoned entry here over
 * silencing a rule at the call site.
 */
export default defineConfig({
  extends: [core, react, next, nextJsPlugins, jsPlugins],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    // Generated by `bun run ui:add` from the shadcn preset and never edited by
    // hand (see AGENTS.md); re-running the generator would undo any fix.
    "components/ui",
    // A farm of symlinks into `.agents/skills`, so Claude Code finds the
    // project's skills where it looks for them. oxlint follows the links, so
    // without this every skill is linted twice under two names – and the
    // second name matches none of the `.agents/skills/**` overrides below, so
    // the same file fails rules the original is exempt from. Lint the real
    // path; the link is the same bytes.
    ".agents/skills",
    ".claude/skills",
  ],
  jsPlugins: jsPlugins.jsPlugins,
  // Type-aware rules run through `oxlint-tsgolint` (typescript-go). The
  // preset already enables them; without this switch they are inert.
  options: { typeAware: true },
  overrides: [
    {
      /*
       * The seam of the functional core (docs/architecture.md, "Functional
       * core, imperative shell"): `lib/` decides, `components/` applies. A
       * module that reads the platform for itself cannot be answered by a
       * table test, which is how the decisions in plans 15, 16 and 22 ended up
       * spread across the effects that carried them out.
       *
       * The adapters are the exception and are listed by name below, one
       * comment each saying which world the file is a window onto. Everything
       * else under `lib/` is a function of its arguments.
       */
      files: ["lib/**"],
      rules: {
        "no-restricted-globals": [
          "error",
          {
            // `window.matchMedia` and `globalThis.fetch` say the same thing as
            // the bare names and have to fail the same way.
            checkGlobalObject: true,
            globals: RESTRICTED_GLOBALS,
          },
        ],
        "no-restricted-imports": [
          "error",
          { paths: [MAPLIBRE, ...DICTIONARIES] },
        ],
      },
    },
    {
      // What the browser runs holds no dictionary either (see DICTIONARIES).
      files: ["components/**"],
      rules: {
        "no-restricted-imports": ["error", { paths: DICTIONARIES }],
      },
    },
    {
      // Server-only modules and the tests may hold both languages: the schema
      // is zod and never reaches the client, `getDictionary` is where the
      // server picks one, and a test reads the German words it checks.
      files: ["lib/schema.ts", "lib/i18n/server.ts", "lib/**/*.test.ts"],
      rules: { "no-restricted-imports": ["error", { paths: [MAPLIBRE] }] },
    },
    {
      files: ["components/**/*.test.ts", "components/**/*.test.tsx"],
      rules: { "no-restricted-imports": "off" },
    },
    // The adapters, one override each. The rule is *re-declared* rather than
    // switched off, minus the globals that file is the window onto: turning it
    // off per file made the comment beside each name unenforced, so nothing
    // stopped the roving-focus hook from reaching for storage. `window` stays
    // allowed wherever the adapter subscribes through it
    // (`window.addEventListener`), which `checkGlobalObject` would otherwise
    // read as a way around every other name.
    {
      // The address bar: the path and `location.hash` in, `router.push` and
      // `history.replaceState` out.
      files: ["lib/hash-adapter.ts"],
      rules: except("history", "location", "window"),
    },
    {
      // The one upstream call the app makes, server-only: Open-Meteo, inside
      // the cached `forecast` with its quota arithmetic and cooldown.
      files: ["lib/weather.ts"],
      rules: except("fetch"),
    },
    {
      // `localStorage` and `sessionStorage`, behind the `STORAGE` table.
      files: ["lib/use-stored.ts"],
      rules: except("localStorage", "sessionStorage", "window"),
    },
    {
      // `window.matchMedia` and the viewport height, as one value per query.
      files: ["lib/use-media-query.ts"],
      rules: except("matchMedia", "window"),
    },
    {
      // `fetch`, as the three answers a request can give.
      files: ["lib/use-fetch.ts"],
      rules: except("fetch"),
    },
    {
      // `ResizeObserver`: what the shell's two bars actually measure.
      files: ["lib/use-height.ts"],
      rules: except("ResizeObserver"),
    },
    {
      // `navigator.share` and the clipboard, with `window.location.href`.
      files: ["lib/use-share.ts"],
      rules: except("location", "navigator", "window"),
    },
    {
      // `MutationObserver` and focus: a list of rows as one composite widget.
      files: ["lib/use-roving.ts"],
      rules: except("MutationObserver"),
    },
    {
      // The explorer hands the shell its parts as slots, and three of them
      // take something only the shell knows: what the bars and panels leave of
      // the map, which of the sidebar's two places is being filled, and which
      // entity the detail drawer still shows while it slides away. They are
      // called, never rendered as an element, so nothing remounts – which is
      // what the rule is there to prevent.
      files: ["components/explorer.tsx"],
      rules: {
        "react/no-unstable-nested-components": [
          "error",
          { allowAsProps: true },
        ],
      },
    },
    {
      // `useFetch<Detail>(url)` names the payload once, at the call. The rule
      // calls a type parameter that only reaches the return type an assertion
      // in disguise – which is what typing a fetched JSON file is.
      files: ["lib/use-fetch.ts"],
      rules: { "typescript/no-unnecessary-type-parameters": "off" },
    },
    {
      // The pipeline serialises its file writes and the transport its
      // API calls per host on promise chains (`writing`, `this.chain`);
      // `await` has no way to hand the chain on to the next caller.
      files: ["scripts/lib/pipeline.ts", "scripts/lib/transport.ts"],
      rules: { "promise/prefer-await-to-then": "off" },
    },
    {
      // The transport keeps its error classes next to the rate limiter that
      // throws them.
      files: ["scripts/lib/transport.ts"],
      rules: { "max-classes-per-file": "off" },
    },
    {
      // The build script talks to rate-limited APIs: requests are sequential
      // on purpose and the retry loop awaits each attempt. The browser
      // harness polls the page the same way: every wait is a loop that must
      // await one probe before deciding whether to make the next one. Both
      // rules say the same thing about the same loops, so both are off here;
      // otherwise the second one pushes exactly these loops into a `while`
      // with a hand-kept index, which is the shape that gets an off-by-one.
      files: ["scripts/**", ".agents/skills/**", "test/**", "e2e/**"],
      rules: {
        "no-await-in-loop": "off",
        "react-doctor/async-await-in-loop": "off",
      },
    },
    {
      // This file *is* the lazily loaded chunk: `detail-panel.tsx` pulls it in
      // through `next/dynamic`, so recharts never reaches the first load.
      files: ["components/panel/climate-chart.tsx"],
      rules: { "react-doctor/prefer-dynamic-import": "off" },
    },
    {
      // Commons serves the photos as ready-made thumbnails from its own CDN
      // (see `lib/photos.ts`): they are already cached, and routing a few
      // hundred of them through the image optimiser would add a hop and a bill
      // for the same bytes. `next/image` also wants every host in
      // `remotePatterns`, which would tie the config to whichever Wikimedia
      // host answers. What it would have brought, the `<img>` carries itself:
      // a `srcset` off Commons' own width ladder and a precomputed
      // placeholder (`photoSrcSet`, `Photo.blur`).
      files: ["components/panel/photo-carousel.tsx"],
      rules: {
        "nextjs/no-img-element": "off",
        "react-doctor/nextjs-no-img-element": "off",
      },
    },
    {
      // The JSON-LD block is the one sanctioned use of the prop. And a
      // `"use cache"` function has to be async even where it awaits nothing:
      // the layout's data is imported JSON, read synchronously (lib/data.ts).
      files: ["app/[[]lang[]]/(explorer)/layout.tsx"],
      rules: { "react/no-danger": "off", "require-await": "off" },
    },
  ],
  rules: {
    // The route gate sits at 25 and `baseReasons` at 21: the pipeline's one
    // decision point and the heuristic both branch a lot by nature, and
    // splitting them would only move the branches.
    complexity: ["error", 25],
    // Guard clauses (`if (!pass) continue;`) and early `return (<jsx/>)` both
    // read fine without braces; no setting of this rule accepts both.
    curly: "off",
    // Base UI components take their element through `render`, which the a11y
    // rules cannot see through, and `role="img"` is the correct label for an
    // inline SVG chart – it is not an `<img>`.
    "jsx-a11y/control-has-associated-label": "off",
    "jsx-a11y/prefer-tag-over-role": "off",
    // Nested ternaries map a status or a scale to a label in one expression –
    // the alternative is an if-chain that says less.
    "no-nested-ternary": "off",
    // `map.on(...)` is cleaned up by `map.remove()` in the same effect.
    "react-doctor/effect-needs-cleanup": "off",
    // 92 passes, 30-odd tours: `includes`, `filter().map()` and friends are
    // clearer than the Set/reduce rewrites these two rules ask for, and none
    // of this is a measured hot path.
    "react-doctor/js-combine-iterations": "off",
    "react-doctor/js-set-map-lookups": "off",
    // `pass-map.tsx` is one component by design (see AGENTS.md); the MapLibre
    // setup does not survive being cut into pieces.
    "react-doctor/no-giant-component": "off",
    // Axis and legend labels in the charts are 11px on purpose; they are dense
    // data annotation, not interface text.
    "react-doctor/no-tiny-text": "off",
    // Route segments and small modules export constants beside a component.
    "react-doctor/only-export-components": "off",
    // The weather route is a Cache Components route: `"use cache"` plus
    // `cacheLife`/`cacheTag` control its freshness, which the rule cannot see.
    "react-doctor/server-fetch-without-revalidate": "off",
    // Handlers are named after what they do (`onOpenScales`), not after the
    // prop they are passed to.
    "react/jsx-handler-names": "off",
    // A handful of effects deliberately opt out of the dependency rules and
    // explain why right above the suppression; this rule objects to the
    // existence of the suppression, which would leave nowhere to put it.
    "react/rule-suppression": "off",
    // An effect that only sometimes has something to clean up returns nothing
    // on the other path. The rule wants `return undefined` there, which
    // `unicorn/no-useless-undefined` in the same preset forbids; between the
    // two, the effect idiom wins.
    "typescript/consistent-return": "off",
    // `onClick={() => setOpen(true)}` is the handler idiom of the whole UI; the
    // block body the rule asks for adds two lines per handler and says less.
    "typescript/no-confusing-void-expression": [
      "error",
      { ignoreArrowShorthand: true },
    ],
    // `noUncheckedIndexedAccess` is on, and the profile, climate and route
    // code walks parallel arrays by index. Guarding every access would bury
    // the maths; the assertions mark the invariant instead.
    "typescript/no-non-null-assertion": "off",
    // Every narrowing `as` is flagged, and most of them are test fixtures
    // (`{ slug, ascents } as Pass`) or parsed JSON typed where it is read.
    // Like the non-null assertion above, the cast marks the invariant.
    "typescript/no-unsafe-type-assertion": "off",
    // A function that hands on a promise it did not make (`() => withPage(…)`
    // in every e2e test) needs neither `async` nor `await`. Together with
    // `return-await: always` this rule rewrites each of them into
    // `async () => await f()`, which says nothing the shorter form does not.
    "typescript/promise-function-async": "off",
    // `if (pass.aliases?.length)` and `if (title)` read as the check they are:
    // absent and empty are the same case everywhere in this code, on purpose.
    // The defaults keep the object case and forbid the other three.
    "typescript/strict-boolean-expressions": [
      "error",
      {
        allowNullableBoolean: true,
        allowNullableNumber: true,
        allowNullableString: true,
      },
    ],
  },
  settings: jsPluginSettings,
});
