import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import { jsPluginSettings, selectJsPlugins } from "ultracite/oxlint/js-plugins";
import next from "ultracite/oxlint/next";
import nextJsPlugins from "ultracite/oxlint/next/js-plugins";
import react from "ultracite/oxlint/react";

const jsPlugins = selectJsPlugins(["react-doctor"]);

/**
 * oxlint replaces ESLint here: its `nextjs` and `react` plugins cover what
 * `eslint-config-next` used to, React Compiler rules included.
 *
 * This file records only where the project deviates from the ultracite preset,
 * and every deviation states why. Prefer adding a reasoned entry here over
 * silencing a rule at the call site.
 */
export default defineConfig({
  extends: [core, react, next, nextJsPlugins, jsPlugins],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    // Generated by `bun run ui:add` from the shadcn preset and never edited by
    // hand (see AGENTS.md); re-running the generator would undo any fix.
    "components/ui",
  ],
  jsPlugins: jsPlugins.jsPlugins,
  settings: jsPluginSettings,
  rules: {
    // ── Style the repo settled on before ultracite ──────────────────────
    // Guard clauses (`if (!pass) continue;`) and early `return (<jsx/>)` both
    // read fine without braces; no setting of this rule accepts both.
    curly: "off",
    // Arrow helpers (`lib/utils.ts`) sit next to function declarations for
    // components; neither is wrong here.
    "func-style": "off",
    // Trailing comments annotate single lines all over `lib/`.
    "no-inline-comments": "off",
    // Nested ternaries map a status or a scale to a label in one expression –
    // the alternative is an if-chain that says less.
    "no-nested-ternary": "off",
    "unicorn/no-negated-condition": "off",
    "no-negated-condition": "off",
    "no-plusplus": "off",
    // Object literals are ordered by meaning, not by name: Next metadata, the
    // manifest, MapLibre paint specs and the scale labels all read in a
    // deliberate sequence that alphabetising would destroy.
    "sort-keys": "off",
    // Components are `function` declarations, hoisted above the helpers they
    // use, and helper declarations follow the component they belong to.
    "no-use-before-define": "off",
    "react/function-component-definition": [
      "error",
      { namedComponents: "function-declaration" },
    ],
    // `x == null` is the deliberate nullish check.
    eqeqeq: ["error", "smart"],
    "no-eq-null": "off",
    "no-multi-assign": "off",
    "no-empty-function": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/prefer-set-has": "off",
    // Named imports from `node:path` read better than a namespace object.
    "unicorn/import-style": "off",
    // Colocated helpers stay next to their only caller; React Compiler takes
    // care of the render cost the preset is worried about.
    "unicorn/consistent-function-scoping": "off",
    "react-doctor/prefer-module-scope-pure-function": "off",
    "react-doctor/prefer-module-scope-static-value": "off",

    // ── Rules that are wrong for this codebase ──────────────────────────
    // `noUncheckedIndexedAccess` is on, and the profile, climate and route
    // code walks parallel arrays by index. Guarding every access would bury
    // the maths; the assertions mark the invariant instead.
    "typescript/no-non-null-assertion": "off",
    // Base UI components take their element through `render`, which the a11y
    // rules cannot see through, and `role="img"` is the correct label for an
    // inline SVG chart – it is not an `<img>`.
    "jsx-a11y/control-has-associated-label": "off",
    "jsx-a11y/prefer-tag-over-role": "off",
    // Handlers are named after what they do (`onOpenScales`), not after the
    // prop they are passed to.
    "react/jsx-handler-names": "off",
    // A handful of effects deliberately opt out of the dependency rules and
    // explain why right above the suppression; this rule objects to the
    // existence of the suppression, which would leave nowhere to put it.
    "react/rule-suppression": "off",
    // `passStatus` and `Explorer` sit at 21: the heuristic and the layout both
    // branch a lot by nature, and splitting them would only move the branches.
    complexity: ["error", 25],
    // 92 passes, 30-odd tours: `includes`, `filter().map()` and friends are
    // clearer than the Set/reduce rewrites these rules ask for, and none of
    // this is a measured hot path.
    "react-doctor/js-set-map-lookups": "off",
    "react-doctor/js-combine-iterations": "off",
    "react-doctor/js-flatmap-filter": "off",
    // Axis and legend labels in the charts are 11px on purpose; they are dense
    // data annotation, not interface text.
    "react-doctor/no-tiny-text": "off",
    // `pass-map.tsx` is one component by design (see AGENTS.md); the MapLibre
    // setup does not survive being cut into pieces.
    "react-doctor/no-giant-component": "off",
    // `map.on(...)` is cleaned up by `map.remove()` in the same effect.
    "react-doctor/effect-needs-cleanup": "off",
    // Route segments and small modules export constants beside a component.
    "react-doctor/only-export-components": "off",
    // The weather route is a Cache Components route: `"use cache"` plus
    // `cacheLife`/`cacheTag` control its freshness, which the rule cannot see.
    "react-doctor/server-fetch-without-revalidate": "off",
    // `useFetch` and the build script drive promises from callbacks on
    // purpose; rewriting them as `await` would need extra state either way.
    "promise/prefer-await-to-then": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/avoid-new": "off",
    "no-promise-executor-return": "off",
    // `scripts/build-data.ts` is a script, not a library: two small classes in
    // one file and TypeScript parameter properties are the point.
    "max-classes-per-file": "off",
    "typescript/parameter-properties": "off",
  },
  overrides: [
    {
      // `"use cache"` requires the function to be async even when it only
      // returns imported JSON.
      files: ["lib/data.ts"],
      rules: { "require-await": "off" },
    },
    {
      // The build script talks to rate-limited APIs: requests are sequential
      // on purpose and the retry loop awaits each attempt. The browser
      // harness polls the page the same way: every wait is a loop that must
      // await one probe before deciding whether to make the next one.
      files: ["scripts/**", ".agents/skills/**", "test/**", "e2e/**"],
      rules: { "no-await-in-loop": "off" },
    },
    {
      // This file *is* the lazily loaded chunk: `detail-panel.tsx` pulls it in
      // through `next/dynamic`, so recharts never reaches the first load.
      files: ["components/panel/climate-chart.tsx"],
      rules: { "react-doctor/prefer-dynamic-import": "off" },
    },
    {
      // The JSON-LD block is the one sanctioned use of the prop.
      files: ["app/page.tsx"],
      rules: { "react/no-danger": "off" },
    },
    {
      // Escape closes the detail panel; the section is the panel, not a
      // control, so it carries the handler.
      files: ["components/panel/detail-panel.tsx"],
      rules: { "jsx-a11y/no-noninteractive-element-interactions": "off" },
    },
    {
      // `setValue` must keep a stable identity – `explorer.tsx` depends on it
      // for its once-only effects. This is not a memoisation for speed.
      files: ["lib/app-state.ts"],
      rules: { "react-doctor/react-compiler-no-manual-memoization": "off" },
    },
  ],
});
