import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import { jsPluginSettings, selectJsPlugins } from "ultracite/oxlint/js-plugins";
import next from "ultracite/oxlint/next";
import nextJsPlugins from "ultracite/oxlint/next/js-plugins";
import react from "ultracite/oxlint/react";

const jsPlugins = selectJsPlugins(["react-doctor"]);

/**
 * `@shadcn/lint` reads `components.json`, so it knows which imports are
 * design-system components and which theme tokens exist. Its rules are the
 * ones AGENTS.md already states in prose – sizes from the scale, colours only
 * via tokens – made checkable.
 */
const shadcnPlugin = { name: "shadcn", specifier: "@shadcn/lint" };

/**
 * What every component in this app may be told from its call site, see
 * `shadcn/no-restyle` below. A contract *replaces* the rule's own `allow`
 * rather than adding to it, so each of them spreads this in first.
 */
const BASE = ["layout", "spacing", "typography"];

/**
 * oxlint replaces ESLint here: its `nextjs` and `react` plugins cover what
 * `eslint-config-next` used to, React Compiler rules included.
 *
 * This file records only where the project deviates from the ultracite preset,
 * and every deviation states why. Prefer adding a reasoned entry here over
 * silencing a rule at the call site.
 */
export default defineConfig({
  extends: [core, react, next, nextJsPlugins, jsPlugins],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    // Generated by `bun run ui:add` from the shadcn preset and never edited by
    // hand (see AGENTS.md); re-running the generator would undo any fix.
    "components/ui",
    // A farm of symlinks into `.agents/skills`, so Claude Code finds the
    // project's skills where it looks for them. oxlint follows the links, so
    // without this every skill is linted twice under two names – and the
    // second name matches none of the `.agents/skills/**` overrides below, so
    // the same file fails rules the original is exempt from. Lint the real
    // path; the link is the same bytes.
    ".agents/skills",
    ".claude/skills",
  ],
  jsPlugins: [...(jsPlugins.jsPlugins ?? []), shadcnPlugin],
  overrides: [
    {
      // `"use cache"` requires the function to be async even when it only
      // returns imported JSON.
      files: ["lib/data.ts"],
      rules: { "require-await": "off" },
    },
    {
      // The build script serialises its API calls and its file writes on
      // promise chains (`this.chain`, `writing`); `await` has no way to hand
      // the chain on to the next caller. It also keeps its error class next
      // to the rate limiter that throws it.
      files: ["scripts/build-data.ts"],
      rules: {
        "max-classes-per-file": "off",
        "promise/prefer-await-to-then": "off",
      },
    },
    {
      // The build script talks to rate-limited APIs: requests are sequential
      // on purpose and the retry loop awaits each attempt. The browser
      // harness polls the page the same way: every wait is a loop that must
      // await one probe before deciding whether to make the next one.
      files: ["scripts/**", ".agents/skills/**", "test/**", "e2e/**"],
      rules: { "no-await-in-loop": "off" },
    },
    {
      // This file *is* the lazily loaded chunk: `detail-panel.tsx` pulls it in
      // through `next/dynamic`, so recharts never reaches the first load.
      files: ["components/panel/climate-chart.tsx"],
      rules: { "react-doctor/prefer-dynamic-import": "off" },
    },
    {
      // Commons serves the photos as ready-made thumbnails from its own CDN
      // (see `lib/photos.ts`): they are already the width the panel asks for
      // and already cached, so routing a few hundred of them through the image
      // optimiser would add a hop and a bill and change nothing about what is
      // downloaded. `next/image` also wants every host in `remotePatterns`,
      // which would tie the config to whichever Wikimedia host answers.
      files: ["components/panel/photo-carousel.tsx"],
      rules: {
        "nextjs/no-img-element": "off",
        "react-doctor/nextjs-no-img-element": "off",
      },
    },
    {
      // The JSON-LD block is the one sanctioned use of the prop.
      files: ["app/page.tsx"],
      rules: { "react/no-danger": "off" },
    },
    {
      // Satori, not a browser: the share image and the mark it paints are laid
      // out by `ImageResponse`, which has no stylesheet, no cascade and no
      // Tailwind – a `style` object is the only way to say anything there. Its
      // palette is `lib/brand.ts` for the same reason (see AGENTS.md): neither
      // Satori nor a manifest can read a CSS variable.
      files: ["app/opengraph-image.tsx", "lib/mark.tsx"],
      rules: { "shadcn/no-inline-styles": "off" },
    },
    {
      // Escape closes the detail panel; the section is the panel, not a
      // control, so it carries the handler.
      files: ["components/panel/detail-panel.tsx"],
      rules: { "jsx-a11y/no-noninteractive-element-interactions": "off" },
    },
    {
      // `setValue` must keep a stable identity – `explorer.tsx` depends on it
      // for its once-only effects. This is not a memoisation for speed.
      files: ["lib/app-state.ts"],
      rules: { "react-doctor/react-compiler-no-manual-memoization": "off" },
    },
  ],
  rules: {
    // `baseVerdict` sits at 21 and `Explorer` at 22: the heuristic and the
    // layout both branch a lot by nature, and splitting them would only move
    // the branches.
    complexity: ["error", 25],
    // Guard clauses (`if (!pass) continue;`) and early `return (<jsx/>)` both
    // read fine without braces; no setting of this rule accepts both.
    curly: "off",
    // Base UI components take their element through `render`, which the a11y
    // rules cannot see through, and `role="img"` is the correct label for an
    // inline SVG chart – it is not an `<img>`.
    "jsx-a11y/control-has-associated-label": "off",
    "jsx-a11y/prefer-tag-over-role": "off",
    // Nested ternaries map a status or a scale to a label in one expression –
    // the alternative is an if-chain that says less.
    "no-nested-ternary": "off",
    // `map.on(...)` is cleaned up by `map.remove()` in the same effect.
    "react-doctor/effect-needs-cleanup": "off",
    // 92 passes, 30-odd tours: `includes`, `filter().map()` and friends are
    // clearer than the Set/reduce rewrites these two rules ask for, and none
    // of this is a measured hot path.
    "react-doctor/js-combine-iterations": "off",
    "react-doctor/js-set-map-lookups": "off",
    // `pass-map.tsx` is one component by design (see AGENTS.md); the MapLibre
    // setup does not survive being cut into pieces.
    "react-doctor/no-giant-component": "off",
    // Axis and legend labels in the charts are 11px on purpose; they are dense
    // data annotation, not interface text.
    "react-doctor/no-tiny-text": "off",
    // Route segments and small modules export constants beside a component.
    "react-doctor/only-export-components": "off",
    // The weather route is a Cache Components route: `"use cache"` plus
    // `cacheLife`/`cacheTag` control its freshness, which the rule cannot see.
    "react-doctor/server-fetch-without-revalidate": "off",
    // Handlers are named after what they do (`onOpenScales`), not after the
    // prop they are passed to.
    "react/jsx-handler-names": "off",
    // A handful of effects deliberately opt out of the dependency rules and
    // explain why right above the suppression; this rule objects to the
    // existence of the suppression, which would leave nowhere to put it.
    "react/rule-suppression": "off",
    // AGENTS.md already draws this line in prose: a size is a step on the
    // scale, and an arbitrary value is only for what the scale genuinely
    // cannot express. These are that list, and it is exhaustive on purpose –
    // a new arbitrary value has to earn an entry here rather than appear in a
    // diff. What is *not* here (a pixel padding, a `text-[13px]`, a radius off
    // the ramp) is what the rule is for.
    "shadcn/no-arbitrary-values": [
      "error",
      {
        allow: [
          // Tailwind's `grid-cols-N`/`grid-rows-N` are equal tracks; every
          // layout here needs a named template (`auto`, `minmax(0,1fr)`).
          "grid-cols-*",
          "grid-rows-*",
          // Declaring a custom property is defining a token, not dodging one.
          // The `--drawer-*` ones steer Vaul, `--sheet-fold` is ours.
          "[--*]",
          // Properties Tailwind has no utility for at all.
          "[content-visibility:auto]",
          "[contain-intrinsic-size:auto_--spacing(12)]",
          "[scrollbar-width:none]",
          // A property list, not a magic number: only `left` animates, so the
          // panel does not repaint its blur on every camera move.
          "transition-[left]",
          // Viewport- and environment-relative, and the row marker AGENTS.md
          // names as the sanctioned inset shadow.
          "max-h-[85vh]",
          "max-w-[calc(100%-4rem)]",
          "pb-[env(safe-area-inset-bottom,0px)]",
          "shadow-[inset_2px_0_0_var(--color-accent)]",
        ],
      },
    ],
    "shadcn/no-inline-styles": "error",
    "shadcn/no-raw-colors": "error",
    /**
     * The one rule that had to be fitted to this app rather than taken as it
     * ships, because its own remedy – "add a variant in components/ui/…" – is
     * closed off here: those files are generated by `bun run ui:add` and never
     * edited by hand, so a domain look has nowhere to live except the call
     * site's `className`. AGENTS.md says as much.
     *
     * Spacing and typography are therefore the app's, not the preset's. This
     * is dense map furniture – a row in the sidebar, a cell in the weather
     * table, a tool in the map cluster – and the preset's comfortable defaults
     * are the wrong size for all of it. The scale still governs which step is
     * taken: `no-arbitrary-values` above is what keeps that honest.
     *
     * Colour and shape stay the design system's, and every exception below is
     * a decision AGENTS.md already writes down in prose. Anything not named
     * here – a new radius on a Card, an ad-hoc tint on a Popover – is a
     * violation, which is the point.
     */
    "shadcn/no-restyle": [
      "error",
      {
        allow: BASE,
        contracts: [
          {
            // The filter chip: "outlined while it is off and filled with the
            // primary colour while it is on", carried by the border as well as
            // the fill so it does not rest on hue alone. The mira preset's
            // pressed Toggle is a faint `bg-muted`, which cannot say that.
            allow: [...BASE, "rounded-full", "border-border", "aria-pressed:*"],
            pattern: "^Toggle$",
          },
          {
            // Three shapes a Button takes here that no variant provides: the
            // pill of the applied-filter chips, the square-cornered full-width
            // row of a sidebar section header, and the small radius of a panel
            // section's title. All three are section furniture rather than
            // buttons, which is also why they drop the ghost variant's hover
            // and `aria-expanded` fills – "a sidebar section adds no surface".
            allow: [
              ...BASE,
              "rounded-full",
              "rounded-none",
              "rounded-sm",
              "hover:bg-transparent",
              "hover:bg-muted/50",
              "aria-expanded:bg-transparent",
              "text-muted-foreground",
              "text-muted-foreground/70",
            ],
            pattern: "^Button$",
          },
          {
            // The map tool cluster and the scrubber's stepper are one panel
            // surface floating over the map (`MAP_CLUSTER`), so the group is
            // translucent and its text label carries no fill of its own.
            allow: [
              ...BASE,
              "bg-background/60",
              "bg-transparent",
              "rounded-md",
            ],
            pattern: "^ButtonGroup(Text)?$",
          },
          {
            // The sheet sits on the bottom edge of the viewport; a radius and
            // a border there are drawn off-screen.
            allow: [...BASE, "rounded-b-none", "border-b-0", "[--*]"],
            pattern: "^DrawerContent$",
          },
          {
            // The weather table's header is secondary text and its freezing
            // temperatures carry the status token the rest of the app uses
            // for a closed pass.
            allow: [...BASE, "text-muted-foreground", "text-status-*"],
            pattern: "^Table(Row|Cell)$",
          },
        ],
      },
    ],
    "shadcn/no-unknown-classes": "error",
    // The rule resolves a constant declared in the same file but not one
    // imported from another, and every one it flags here is the latter:
    // `TOUCH_CONTROL`, `MAP_CONTROL`, `MAP_TOOL`, `ICON_TOGGLE`, `PRESSED` in
    // `lib/utils.ts` are plain string literals, hoisted precisely so the one
    // decision behind them (see AGENTS.md on touch targets and map furniture)
    // is written down once. Inlining them to satisfy the rule would scatter
    // that decision over a dozen call sites, which is the opposite of what the
    // rule is for. `no-restyle` reads through `cn()` regardless.
    "shadcn/require-static-classes": "off",
    // `noUncheckedIndexedAccess` is on, and the profile, climate and route
    // code walks parallel arrays by index. Guarding every access would bury
    // the maths; the assertions mark the invariant instead.
    "typescript/no-non-null-assertion": "off",
  },
  settings: jsPluginSettings,
});
